"""Reusable teleop parameter profiles for sigma7_psm_teleop.py.

Keys use argparse destination names, so command-line options like
`--orientation-mode` become `orientation_mode`.
"""

TELEOP_CONFIGS = {
    "split_antijitter_keep_rot": {
        "orientation_mode": "split",
        "track_body": "tool_wrist",
        "orientation_body": "tool_tip",
        "position_frame": "world",
        "scale_x": 0.55,
        "scale_y": 0.55,
        "scale_z": 0.45,
        "orientation_gain": 0.28,
        "damping_pos": 0.00075,
        "damping_full": 0.0024,
        "max_position_error": 0.006,
        "max_orientation_error": 0.18,
        "max_joint_step": 0.004,
        "dq_deadband": 0.00011,
        "target_smooth": 0.20,
        "dq_smooth": 0.22,
        "split_distal_smooth": 0.16,
        "ctrl_smooth": 0.16,
        "max_ctrl_step_pos": 0.0020,
        "max_ctrl_step_ins": 0.00038,
        "max_ctrl_step_roll": 0.0022,
        "hybrid_insertion_dq_scale": 0.22,
        "hybrid_dq_smooth_ins": 0.08,
        "split_distal_step_scale": 0.7,
        "limit_slowdown_margin": 0.16,
        "limit_slowdown_min_scale": 0.10,
        "jaw_mode": "follow",
        "gripper_close_deg": 0.0,
        "gripper_open_deg": 1.6,
        "jaw_smooth": 0.18,
        "jaw_deadband": 0.002,
        "max_ctrl_step_jaw": 0.03,
        "print_every": 0.08,
        "log_every": 0.08,
        "log_csv": "Logs/split_config_run.csv",
    },
    "split_wider_motion": {
        "orientation_mode": "split",
        "track_body": "tool_wrist",
        "orientation_body": "tool_tip",
        "position_frame": "world",
        "scale_x": 0.70,
        "scale_y": 0.70,
        "scale_z": 0.55,
        "orientation_gain": 0.32,
        "damping_pos": 0.00065,
        "damping_full": 0.0020,
        "max_position_error": 0.008,
        "max_orientation_error": 0.22,
        "max_joint_step": 0.005,
        "dq_deadband": 0.00009,
        "target_smooth": 0.22,
        "dq_smooth": 0.24,
        "split_distal_smooth": 0.18,
        "ctrl_smooth": 0.18,
        "max_ctrl_step_pos": 0.0026,
        "max_ctrl_step_ins": 0.00045,
        "max_ctrl_step_roll": 0.0028,
        "hybrid_insertion_dq_scale": 0.28,
        "hybrid_dq_smooth_ins": 0.09,
        "split_distal_step_scale": 0.85,
        "limit_slowdown_margin": 0.10,
        "limit_slowdown_min_scale": 0.18,
        "jaw_mode": "follow",
        "gripper_close_deg": 0.0,
        "gripper_open_deg": 1.6,
        "jaw_smooth": 0.18,
        "jaw_deadband": 0.002,
        "max_ctrl_step_jaw": 0.03,
        "print_every": 0.08,
        "log_every": 0.08,
        "log_csv": "Logs/split_wider_motion.csv",
    },
}


DEFAULT_PROFILE = "split_antijitter_keep_rot"
